version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - redis-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
      # - REDIS_PASSWORD=${REDIS_PASSWORD}  # 如果需要密码认证，取消注释并在.env中设置密码
    restart: unless-stopped
    networks:
      - redis-network
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  redis-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: redis-bridge

volumes:
  redis-data:
    driver: local